version: 2
jobs:
  build:
    docker:
      - image: openjdk:8-alpine
    branches:
        only:
            - main
    steps:
        - checkout
        - run:
            name: Build
            command: mvn clean install