version: 2
jobs:
  build:
    docker:
      - image: maven:3.6.3-jdk-8
    branches:
        only:
            - main
    steps:
        - checkout
        - run:
            name: Build
            command: mvn compile
        - run:
            name: Test
            command: mvn test